---
language: python
python: "2.7"

sudo: required
dist: trusty

env:
  global:
    - VAGRANT_URL=https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5_x86_64.deb
    - VAGRANT_SHA256SUM=30ee435c3358c6a835ea52cf710f4e50caa0e77cb721332132a2d3386a8745d9

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y rsync
  - curl -Lo vagrant.deb "${VAGRANT_URL}"
  - sha256sum vagrant.deb
  - echo "${VAGRANT_SHA256SUM}  vagrant.deb" | sha256sum -c
  - sudo dpkg -i vagrant.deb
  - sudo apt-get install -y libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev qemu-kvm libvirt-bin
  # Use libvirt plugin 0.0.35 to avoid "dhcp_leases: undefined method"
  # see https://github.com/vagrant-libvirt/vagrant-libvirt/issues/669 for detail
  - vagrant plugin install vagrant-libvirt --plugin-version 0.0.35

install:
  - pip install ansible ansible-lint
  - ansible --version
  - ansible-lint --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg
  - pushd tests
  # after `adduser travis libvirtd`, re-login is required to take effect, so run with sudo
  - sudo vagrant up freebsd --provider=libvirt --no-provision
  - sudo vagrant provision freebsd --provision-with bootstrap
  - popd

script:
  - ansible-playbook -i localhost, --syntax-check --extra-vars=role_dir_name=${PWD##*/} tests/test.yml 
  - ansible-lint tests/test.yml
  - pushd tests
  # after `adduser travis libvirtd`, re-login is required to take effect, so run with sudo
  - travis_wait 40 sudo ./provision-ansible.sh
  - sudo vagrant provision freebsd --provision-with test
  - popd

notifications:
  email: false
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/

