# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define :freebsd do |freebsd|
    freebsd.vm.box = "generic/freebsd11"

    freebsd.vm.provider :libvirt do |v|
      v.driver = 'qemu'
      v.nested = 'yes'
      v.memory = 2048
      v.graphics_type = 'none'
    end

    freebsd.vm.synced_folder ".", "/vagrant", type: 'rsync'

    freebsd.vm.provision "bootstrap", type: "shell", inline: "sudo pkg install -q -y python2"

    freebsd.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.raw_arguments = [
        "--extra-vars=roles_path=../../",
        "--extra-vars=role_dir_name=#{File.basename(File.dirname(ENV['PWD']))}",
        "--extra-vars=ansible_python_interpreter=/usr/local/bin/python2.7",
      ]
    end

    freebsd.vm.provision "test", type: "shell", inline: <<-SHELL
      uname -a
      freebsd-version
      pkg update -q
      pkg install -q -y ca_root_nss curl
      curl -v -L https://raw.github.com/rylnd/shpec/master/install.sh
      echo "curl exited with $?"
      curl -sL https://raw.github.com/rylnd/shpec/master/install.sh | sudo sh -x
      (cd /vagrant && shpec)
    SHELL
  end
end
