# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define :freebsd do |freebsd|
    freebsd.vm.box = "generic/freebsd11"

    freebsd.vm.provider :libvirt do |v|
      v.driver = 'qemu'
      v.memory = 2048
      v.graphics_type = 'none'
    end

    freebsd.vm.synced_folder ".", "/vagrant", type: 'rsync'

    freebsd.vm.provision "bootstrap", type: "shell", inline: "sudo pkg install -q -y python2"

    freebsd.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
      ansible.raw_arguments = [
        "--extra-vars=roles_path=../../",
        "--extra-vars=role_dir_name=#{File.basename(File.dirname(ENV['PWD']))}",
        "--extra-vars=ansible_python_interpreter=/usr/local/bin/python2.7",
      ]
    end

    freebsd.vm.provision "test", type: "shell", inline: <<-SHELL
      pkg update -q
      pkg install -q -y ca_root_nss curl
      mkdir -p /tmp/shpec
      tar zxf /vagrant/shpec.tar.gz --strip-component 1 -C /tmp/shpec
      (cd /tmp/shpec && make install) && rm -rf /tmp/shpec
      (cd /vagrant && shpec)
    SHELL
  end
end
